### PR TITLE
EZP-26870: Upgrade ezmultiupload to YUI 3

### PR DESCRIPTION
**Pull request by glye**
> Implement https://jira.ez.no/browse/EZP-26870
> Addendum to https://github.com/ezsystems/ezmultiupload/pull/16
> Ready for review

The YUI 3 bundled with ezjscore for ezp 4.x is too old for the HTML5 upload feature used in ezmultiupload for YUI 3. This upgrades to YUI 3.18.1, and updates `ezjscore.ini`. It should be merged in 1.5, 1.4, 1.3 (ezp 4.7, 4.6, 4.5).

### CODE REVIEW

**Comment by glye** [comment]
Gargantuan review ping @dpobel @yannickroger @andrerom

**Comment by andrerom** [comment]
hmm, maybe better to do a 1.6 based on the 5.x version, but if that is not an option: +1

**Comment by glye** [comment]
@andrerom We need it only for 4.x. If we upgrade for 5.x too QA will not be happy, as those tests are completed. But say the word and it shall happen :)

**Comment by andrerom** [comment]
I wasn't suggesting updating 5.x, I was saying making a 1.6 version for 4.x based on what we already have in 5.x. I assume 5.x versions still supported has a newer version of YUI already.

**Comment by glye** [comment]
I see. This is possible, only cost is more time spent by me, reviewers and QA since QA was working in parallell on this and has just approved it on 4.x. So please just make clear if you consider it worthwhile. For example if the upgrade risk is lower that way, I don't know.

For the legacy patch system the risk is higher as the patch becomes bigger and more complex. It's currently at 65 MB, which will grow to maybe 80 MB with a new ezjscore branch.

**Review by andrerom — APPROVED** [review]
No this is ok for this case

**Comment by glye** [comment]
Review ping @dpobel @yannickroger

**Comment by yannickroger** [comment]
+1 if QA agrees
My browser can't even load the "File changed" tab. I can't approve or review but we have no choice with this kind of changes.

**Comment by glye** [comment]
QA approved, merging.

**Pull request merged**
