### PR TITLE
Fixed wrong links after eZPublish Legacy repo rename.

### PR DESCRIPTION
**Pull request by crevillo**
Those links were broken after the rename of the repos. 
Let me know if do you need an issue in the tracker for this or this pr could be enough.

### CODE REVIEW

**Comment by nfrp** [comment]
Hi Carlos, good catch. If you find a little time to report an issue that would be ideal!
:+1: for me anyways.

**Comment by lolautruche** [comment]
Thanks @crevillo !

**Comment by crevillo** [comment]
Issue added: https://jira.ez.no/browse/EZP-20745
Feel free to mark it as fixed :)

**Comment by lolautruche** [comment]
@crevillo did you check in the main repository, now that `ezjscore` is part of it ?

**Comment by nfrp** [comment]
Thanks Carlos btw!

**Comment by crevillo** [comment]
@lolautruche which check do you mean?

**Comment by lolautruche** [comment]
Forget it, I misread which file your patch fixed :blush:

**Comment by crevillo** [comment]
ah, hehe. :+1:

**Pull request merged**
