### PR TITLE
Issue018025

### PR DESCRIPTION
**Pull request by crevillo**
Please see the issue for discussion. this pull request also includes my previous one. so if this is merged no need to look for the previous one.

### CODE REVIEW

**Comment by nfrp** [comment]
Thanks you Carlos !

**Comment by andrerom** [comment]
Not so sure about the second commit. There are very few sites serving xhtml as xml because of missing support in IE.

So I haven't seen use of CData in the wild since around 2003/4 when people tried and failed at serving xhtml as xml, and some of the threads mentions issues in some browsers, and while you handle that with comments in the script tag, you don't in the style tag( // is a js comment, not sgml / css comment).

**Comment by crevillo** [comment]
I see your point...  my patch came after reading https://developer.mozilla.org/en/properly_using_css_and_javascript_in_xhtml_documents. but yep, probably it can be improved... 
at first chance, jqueryio and yuiio outputs the code and it makes validation fails... recommendation in that document says it could be better move it to a external file... any chance to do that?

**Comment by andrerom** [comment]
It is placed in external file if you enable packing, but it's not when it is disabled since there is no source file.
Btw, check the date on that Mozille page, this is largely outdated in a html5 context.

**Comment by crevillo** [comment]
Wasp... good point...

**Comment by andrerom** [comment]
(IMO) If Microsoft's html-polygot\* proposal is recommended by w3c and implemented in browsers, as well as xhtml5 support gets widespread. Then we can seriously re consider xhtml.
- http://www.w3.org/TR/html-polyglot/
  http://dev.w3.org/html5/html-xhtml-author-guide/html-xhtml-authoring-guide.html#in-line-script-and-style

But, your cdata change on script tags are valid in all modes, so we can consider adding it, but not for the style tag.
Would that be ok? Given that it's not so common to have < or & in css code I think this can work. or?

**Comment by crevillo** [comment]
ok. perfect. yeah, i don't know any case of '&' or '<' used in css. 
thanks!

**Comment by crevillo** [comment]
btw, do you want me to recommit and add another pull request or something? let me know. cheers.

**Comment by andrerom** [comment]
I merged it manually instead: https://github.com/ezsystems/ezjscore/commit/c84e862cbd033403bd34508f218ba2c1c163fc45
Thanks for the patch,, and hope it helps ;)

**Comment by crevillo** [comment]
great!. thanks a lot.

**Pull request closed without merging**
