### PR TITLE
Added CSS optimizer to inline small image files as a Data URL.

### PR DESCRIPTION
**Pull request by johanberonius**
Not sure if this is the best place for this feature.
I originally developed this feature as a patch for 'ezjscpacker.php' in our installation of eZ Publish 4.5.
When I later adapted it for the latest version of ezjscore I discovered that optimizers are now configurable and can be loaded from any class. I guess that way they can be placed in any extension.
If you don't thinks this fit here, please give me a tip on the best way to share this code.

### CODE REVIEW

**Comment by andrerom** [comment]
This is awesome :)

And as for including it or not, that boils down to a few things:
- Have you tested this extensively? Especially the regex might be a point of failure.
- Could you send us a CLA? Needed for code contributions like this, see: http://share.ez.no/community-project/contributor-licensing-agreement-cla

**Comment by johanberonius** [comment]
Not really tested extensively yet.
As for the RegExp, it's the same as used in ezjscPacker::fixImgPaths(), I copied it from there.

**Comment by johanberonius** [comment]
I don't care much for copyright so let's just call it a "small patch" that doesn't need the CLA. Feel free to use the code if you like.

**Comment by andrerom** [comment]
I would like to, but as I have strict instructions to ask for CLA, I'll have to pass on it for now.
Noticed there is an extensions for this now, so people who want it can use that one.

**Pull request closed without merging**
