### PR TITLE
Content returned from a server function that requests not to be cached.

### PR DESCRIPTION
**Pull request by johanberonius**
I'd like to use this pull request to discuss the code on line 304 of ezjscpacker.

I understand that some js server functions can request not to be cached by returning -1 from getCacheTime. They do this because they add other files instead and therefore they do not return any content other than the empty string.
But if they were to return any content, since it's added to $data['locale'] array, it's treated as the filename of a local file to be included in the generated cache file. If it's not a valid filename that will cause a PHP warning "file_get_contents: failed to open stream: No such file or directory"

If any returned content is added to the $data['http'] array instead, it's then treated as an URL to an external javascript resource or as a fragment of javascript code to be included inline in its own script-tag. It is possible to add external URLs to the file array today, but it is not possible to insert any javascript code beside the cache file and external URLs.

I've come around this problem since I need to prevent some javascript fragments from being included in the cache file. Almost every page on our site requires a few fragments of unique javascript code and that is causing ezjscpacker to generate a unique cache file for every page on the entire site.

### CODE REVIEW

**Comment by andrerom** [comment]
The change makes sense, and on first look I can only see one potential regression with this change:

```
    else if ( !$data['locale'] )
    {
        eZDebug::writeWarning( "Could not find any files: " . var_export( $fileArray, true ), __METHOD__ );
        return array();
    }
```

**Comment by johanberonius** [comment]
I've noticed that check. Is that the only reason why an empty string is added to $data['locale'], just as a flag so that check will not fail?

This check also fails if there are only external URLs and no local files for the packer to cache. Then they are lost since and empty array is returned instead of $data['http']

Another minor issue, in printDebugReportFiles() empty strings are skipped for local files but not for http URLs.

**Comment by andrerom** [comment]
>  just as a flag so that check will not fail?

Unsure, written long time ago :)

> Another minor issue, in printDebugReportFiles() empty strings are skipped for local files but not for http URLs.

True.

**Comment by johanberonius** [comment]
I have discovered three scenarios where the packer behaves badly. (Like the code is now, not after the change in my commit)
- If a page only loads one javascript with a server function (for example `ezjsc:jquery`) it will cache even a single file. This is due to `$data['locale']` contains both an empty string and a filename so the check on [line 388](https://github.com/ezsystems/ezjscore/blob/master/classes/ezjscpacker.php#L388) will not catch this.
- If a page only loads one javascript with a server function (for example `ezjsc:jquery`) and `LoadFromCDN=enabled` it will create an empty cache file in addition to the script tag for the external script URL. This is due to `$data['locale']` only contains an empty string which is false and the check on [line 388](https://github.com/ezsystems/ezjscore/blob/master/classes/ezjscpacker.php#L388) will not catch this.
- If a page only loads one javascript with an external URL (for example http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js) it will warn "Could not find any files" and not print any script tag at all! This is due to `$data['locale']` being empty and the check on [line 383](https://github.com/ezsystems/ezjscore/blob/master/classes/ezjscpacker.php#L383) return an empty array when it should return `$data['http']`. Also the array in the warning message on [line 385](https://github.com/ezsystems/ezjscore/blob/master/classes/ezjscpacker.php#L385) is also empty since the while-loop has just shifted all values from $fileArray.

**Comment by andrerom** [comment]
Well, how would it look if you combine your patch with:

```
-    else if ( !$data['locale'] )
+    else if ( empty( $data['locale'] ) && empty( $data['http'] ) )
```

**Comment by johanberonius** [comment]
I have added another check before the `!$data['locale']` one to test if there are some external scripts in `$data['http']` but `$data['locale']` is empty, in that case just return the external scripts and skip caching since there are no local files to cache.

This fixes all of the three above mentioned bugs.

Also, `$originalFileArray` is set just to be able to print the debug message with the original content of the file array.

And in `printDebugReportFiles()` it now also skips empty strings for external scripts.

**Comment by johanberonius** [comment]
Do you need a signed CLA even for a small fix like this? I guess I could do that, it's no big deal.

**Comment by andrerom** [comment]
no, I can manually merge it and attribute the original idea to you and then you don't need it for this one.

**Comment by andrerom** [comment]
Manually merged, closing, thanks for the patch! :)

**Pull request closed without merging**
