### PR TITLE
ezscriptfiles_load operator

### PR DESCRIPTION
**Pull request by gbentley**
New template operator which combines the power of ezscriptfiles with ezscript_load.

While ezscriptfiles can load (or optionally ignore) files requested with ezscript_require, you cannot separate these from "site-wide" js files set in design.ini.

ezscriptfiles_load() allows you to load only page-specific files and output as an array of file paths.

### CODE REVIEW

**Comment by gggeek** [comment]
Functionality looks interesting, but the name of the operator is imho not very clear...

**Comment by gbentley** [comment]
**Summary**: Happy to implement this as **optional parameter for ezscript/ezscript_load**.

---

It is a little verbose. Any suggestions for alternative?  It's a simple combo of _ezscriptfiles_ & _ezscript_load_ (as it combines functionality from both.  

**ezscript**  -  outputs files from design.ini (or param) as **_script tags**_
**ezscriptfiles** - outputs files from design.ini (or param) & those requested with ezscript_require (optionally ignored) as **_array of filenames**_

**ezscript_load** - outputs files requested with ezscript_require (or params) as **_script tags**_
**ezscriptfiles_load** - outputs files requested with ezscript_require (or param) as **_array of filenames**_

See http://share.ez.no/forums/extensions/ezscriptfiles-equivalent-for-ezscript_load for use-case.

The _ezscriptfiles_ functionality which pulls in _ezscript_require_ files should possibly also be **removed**, to be in line with the functionality of _ezscript_ (this would break BC).

A _cleaner solution_ would be to give _ezscript_ and _ezscript_load_ an optional parameter to output as **array of filenames**, and remove _ezscriptfiles_ entirely (removal of _ezscriptfiles_ would break BC, so perhaps leave this part out). 

Happy to implement this as **optional parameter for ezscript/ezscript_load** if you think this is a cleaner solution.

**Comment by gggeek** [comment]
I guess you see the "load" concept a bit differently than I do.

To me:
ezscript_require: declare needed files
ezscript_load: include in html the link to the needed files, which have been magically packed
ezscriptfiles: get as an array the names of the magically packed files

I actually use so seldom ezscript that I had to look up in the code what it does.

Apart from that, ezscriptfiles should imho be a arbon copy of ezscript_load...

**Comment by gbentley** [comment]
The key here is separation of site-wide JS from page-specific JS.  ezscript & ezscript_load provide this.  ezscriptfiles does not.  ezscriptfiles pulls in both (unless page-specific is ignored) JS files from design.ini settings _and_ from ezscript_require.

There is currently no way to get _only_ page-specific JS as an array of filenames (or one packed file).  This pull request attempts to resolve that.

**Comment by nfrp** [comment]
Looks very good @gbentley !
I think we will benefit from @andrerom 's or  @dpobel 's expert eyes on this one !

**Comment by andrerom** [comment]
Looks good, but should add ezcssfiles_load while on it, otherwise it's inconsistent :)

**Comment by gbentley** [comment]
True.  What are your thoughts on adding a parameter to ezscript/ezscript_load (& ezcss/ezcss_load) instead of, or in addition to, the "files" functions?

**Comment by andrerom** [comment]
I don't have a strong opinion pro/against, what do you think is more consistent yourself?

**Comment by gbentley** [comment]
I'm personally in favour of having an extra parameter to change output - extra functions seems overkill, and ezscriptfiles functionality combines both ezscript/_load which I don't feel is consistent with simply changing the output format of ezscript/_load.

Removing ezscriptfiles breaks BC, but functionality is easily replicable through using ezscript/_load with an extra parameter to change the output format.

On the other hand, creating as an extra parameter is more work :-)

**Comment by gggeek** [comment]
+1 for adding a parameter rather than extra functions

**Comment by andrerom** [comment]
+1 on adding parameters, so closing this PR as I'm in the middel of moving systems extensions to eZ Publish 4.x repo.

**Pull request closed without merging**
