### PR TITLE
www_dir should be set in the returned uri only if the cache_dir is not a...

### PR DESCRIPTION
**Pull request by zeitounator**
In site.ini, it is possible to set the cacheDir as an absolute path. In that case, the uri of the ezjscore packed files should not contain the www_dir preprended to the cache path or it leads to errors (i.e. href="//my/path" leading the navigator trying to load the ressource "path" from server "my").

Here is a small patch which does the job according to my first tests.

### CODE REVIEW

**Comment by andrerom** [comment]
Cache dir refers to internalt disk structure if absolute isn't it? So not something that needs or can be exposes in the http url.

**Comment by zeitounator** [comment]
If you don't expose the cache path, how are you going to know the path to the generated cache files and have a specific rewrite rule for that in your vhost ?

Forgot to mention that, of course, if you define an absolute path to cache files, the "standard" ezjscore/texttoimage rewriteRule (RewriteRule ^/var/([^/]+/)?cache/(texttoimage|public)/.\* - [L]) is useless and needs to be rewrittent (in my case something like RewriteRule ^/path/to/absolutedir/(texttoimage|public)/.\* - [L]). Same thing if you use a cluster setup.

**Comment by zeitounator** [comment]
The only simple solution I see to this problem is leaving the cache dir untouched as a subdir of VarDir and set the filesystem path as a symbolic link (cd vardir && ln -s /path/to/my/absolutecache cache).... but I really don't like it.

**Comment by andrerom** [comment]
> VarDir and set the filesystem path as a symbolic link (cd vardir && ln -s /path/to/my/absolutecache cache)

This is afaik how most people setup nfs mount disk inside var folder.

Also I think you have miss understood www dir, it is used in cases where eZ Publish is placed in a sub directory (example.com/ezpublish/*), hence your patch would potentially further break these setups.

**Comment by zeitounator** [comment]
I don't think I misunderstood.

Let's say I have ez in a ezpublish subdir on my host and  that vardir is the default (var)
- web path to var  is /ezpublish/var
- I get images in /ezpublish/var/images
- I get generated ezjscore cache files in /ezpublish/var/cache/public

Now if I set a CacheDir=/my/ezcache
- web path  to  var is unchanged
- images are still in /ezpublish/var/images and are not at all affected by my patch

In the current situation (without my patch) ezjscore path will be outputed as (notice double slash) /ezpublish//my/ezcache/public  which is wrong in any case.  In  case ez is installed at the root of my web server, the path will be //my/ezcache/public which is  even worse (the request will not even get to my server).

With my patch, the path  will be set in both  cases to /my/ezcache/public which is far from  perfect I agree but solves my immediate problem, does not  brake installs with subdirs, and ensure the request still get to the server and can be matched with a rewriterule.

I think the real problem is that cachedir was not originally meant to contain generated files directly accessible with a url and that we have an issue when setting it with an absolute path (so goes with texttoimage which I did not dig into).

I don't see a nice solution to work arround this problem but I'll be glad to help in any way.

**Comment by patrickallaert** [comment]
This PR as well as https://github.com/ezsystems/ezpublish/pull/287 are going to be analyzed in the frame of solving issue: http://issues.ez.no/19140

**Comment by bdunogier** [comment]
Won't merge. See the reasons on https://github.com/ezsystems/ezpublish/pull/287.

**Pull request closed without merging**
